title: Andrés Saldívar Martínez
description: Hola! Check out some of the projects I've worked on in this portfolio.
logo: /assets/img/nopal.png
theme: jekyll-theme-minimal
# Markdown engine recomendado por Jekyll
markdown: kramdown
author:
  name: Andrés Saldívar
  email: andres.saldivar@gmail.com
  linkedin: https://linkedin.com/in/andressaldivarda
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
